name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - uses: Trim21/setup-poetry@dist/v1

      - uses: Trim21/install-poetry-project@dist/v1

      - name: test
        run: coverage run -m pytest

      - run: bash <(curl -s https://codecov.io/bash) -F ${{ matrix.python }}

  dist-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - uses: Trim21/setup-poetry@dist/v1

      - run: poetry build

      - name: Install twine
        run: pip install twine

      - name: Check Files
        run: twine check dist/*
