name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
      - uses: Trim21/setup-poetry@dist/v1

      - run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
      - run: npm i conventional-changelog@3
      - run: node .github/scripts/changelog.mjs | tee changelog.md

      - name: Upload Github Release
        run: gh release create "$TAG" -F changelog.md ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
